// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.energyos.espi.datacustodian.domain;

import java.lang.String;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.energyos.espi.datacustodian.domain.DataCustodian;
import org.springframework.stereotype.Component;

privileged aspect DataCustodianDataOnDemand_Roo_DataOnDemand {
    
    declare @type: DataCustodianDataOnDemand: @Component;
    
    private Random DataCustodianDataOnDemand.rnd = new SecureRandom();
    
    private List<DataCustodian> DataCustodianDataOnDemand.data;
    
    public DataCustodian DataCustodianDataOnDemand.getNewTransientDataCustodian(int index) {
        DataCustodian obj = new DataCustodian();
        setDescription(obj, index);
        setName(obj, index);
        return obj;
    }
    
    public void DataCustodianDataOnDemand.setDescription(DataCustodian obj, int index) {
        String description = "description_" + index;
        if (description.length() > 512) {
            description = description.substring(0, 512);
        }
        obj.setDescription(description);
    }
    
    public void DataCustodianDataOnDemand.setName(DataCustodian obj, int index) {
        String name = "name_" + index;
        if (name.length() > 30) {
            name = name.substring(0, 30);
        }
        obj.setName(name);
    }
    
    public DataCustodian DataCustodianDataOnDemand.getSpecificDataCustodian(int index) {
        init();
        if (index < 0) index = 0;
        if (index > (data.size() - 1)) index = data.size() - 1;
        DataCustodian obj = data.get(index);
        return DataCustodian.findDataCustodian(obj.getId());
    }
    
    public DataCustodian DataCustodianDataOnDemand.getRandomDataCustodian() {
        init();
        DataCustodian obj = data.get(rnd.nextInt(data.size()));
        return DataCustodian.findDataCustodian(obj.getId());
    }
    
    public boolean DataCustodianDataOnDemand.modifyDataCustodian(DataCustodian obj) {
        return false;
    }
    
    public void DataCustodianDataOnDemand.init() {
        data = DataCustodian.findDataCustodianEntries(0, 10);
        if (data == null) throw new IllegalStateException("Find entries implementation for 'DataCustodian' illegally returned null");
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<org.energyos.espi.datacustodian.domain.DataCustodian>();
        for (int i = 0; i < 10; i++) {
            DataCustodian obj = getNewTransientDataCustodian(i);
            try {
                obj.persist();
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> it = e.getConstraintViolations().iterator(); it.hasNext();) {
                    ConstraintViolation<?> cv = it.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
