/*******************************************************************************
 * Copyright (c) 2011, 2012 EnergyOS.Org
 *
 * Licensed by EnergyOS.Org under one or more contributor license agreements.
 * See the NOTICE file distributed with this work for additional information
 * regarding copyright ownership.  The EnergyOS.org licenses this file
 * to you under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License.  You may obtain a copy
 * of the License at:
 *  
 *   http://www.apache.org/licenses/LICENSE-2.0
 *  
 *  Unless required by applicable law or agreed to in writing,
 *  software distributed under the License is distributed on an
 *  "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 *  KIND, either express or implied.  See the License for the
 *  specific language governing permissions and limitations
 *  under the License.
 *  
 ******************************************************************************
*/


// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.energyos.espi.datacustodian.domain;

import java.util.List;
import org.energyos.espi.datacustodian.domain.DataCustodian;
import org.energyos.espi.datacustodian.domain.DataCustodianDataOnDemand;
import org.energyos.espi.datacustodian.domain.DataCustodianIntegrationTest;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect DataCustodianIntegrationTest_Roo_IntegrationTest {
    
    declare @type: DataCustodianIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: DataCustodianIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: DataCustodianIntegrationTest: @Transactional;
    
    @Autowired
    DataCustodianDataOnDemand DataCustodianIntegrationTest.dod;
    
    @Test
    public void DataCustodianIntegrationTest.testCountDataCustodians() {
        Assert.assertNotNull("Data on demand for 'DataCustodian' failed to initialize correctly", dod.getRandomDataCustodian());
        long count = DataCustodian.countDataCustodians();
        Assert.assertTrue("Counter for 'DataCustodian' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void DataCustodianIntegrationTest.testFindDataCustodian() {
        DataCustodian obj = dod.getRandomDataCustodian();
        Assert.assertNotNull("Data on demand for 'DataCustodian' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'DataCustodian' failed to provide an identifier", id);
        obj = DataCustodian.findDataCustodian(id);
        Assert.assertNotNull("Find method for 'DataCustodian' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'DataCustodian' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void DataCustodianIntegrationTest.testFindAllDataCustodians() {
        Assert.assertNotNull("Data on demand for 'DataCustodian' failed to initialize correctly", dod.getRandomDataCustodian());
        long count = DataCustodian.countDataCustodians();
        Assert.assertTrue("Too expensive to perform a find all test for 'DataCustodian', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<DataCustodian> result = DataCustodian.findAllDataCustodians();
        Assert.assertNotNull("Find all method for 'DataCustodian' illegally returned null", result);
        Assert.assertTrue("Find all method for 'DataCustodian' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void DataCustodianIntegrationTest.testFindDataCustodianEntries() {
        Assert.assertNotNull("Data on demand for 'DataCustodian' failed to initialize correctly", dod.getRandomDataCustodian());
        long count = DataCustodian.countDataCustodians();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<DataCustodian> result = DataCustodian.findDataCustodianEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'DataCustodian' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'DataCustodian' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void DataCustodianIntegrationTest.testFlush() {
        DataCustodian obj = dod.getRandomDataCustodian();
        Assert.assertNotNull("Data on demand for 'DataCustodian' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'DataCustodian' failed to provide an identifier", id);
        obj = DataCustodian.findDataCustodian(id);
        Assert.assertNotNull("Find method for 'DataCustodian' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyDataCustodian(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'DataCustodian' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void DataCustodianIntegrationTest.testMergeUpdate() {
        DataCustodian obj = dod.getRandomDataCustodian();
        Assert.assertNotNull("Data on demand for 'DataCustodian' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'DataCustodian' failed to provide an identifier", id);
        obj = DataCustodian.findDataCustodian(id);
        boolean modified =  dod.modifyDataCustodian(obj);
        Integer currentVersion = obj.getVersion();
        DataCustodian merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'DataCustodian' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void DataCustodianIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'DataCustodian' failed to initialize correctly", dod.getRandomDataCustodian());
        DataCustodian obj = dod.getNewTransientDataCustodian(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'DataCustodian' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'DataCustodian' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        Assert.assertNotNull("Expected 'DataCustodian' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void DataCustodianIntegrationTest.testRemove() {
        DataCustodian obj = dod.getRandomDataCustodian();
        Assert.assertNotNull("Data on demand for 'DataCustodian' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'DataCustodian' failed to provide an identifier", id);
        obj = DataCustodian.findDataCustodian(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'DataCustodian' with identifier '" + id + "'", DataCustodian.findDataCustodian(id));
    }
    
}
