/*******************************************************************************
 * Copyright (c) 2011, 2012 EnergyOS.Org
 *
 * Licensed by EnergyOS.Org under one or more contributor license agreements.
 * See the NOTICE file distributed with this work for additional information
 * regarding copyright ownership.  The EnergyOS.org licenses this file
 * to you under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License.  You may obtain a copy
 * of the License at:
 *  
 *   http://www.apache.org/licenses/LICENSE-2.0
 *  
 *  Unless required by applicable law or agreed to in writing,
 *  software distributed under the License is distributed on an
 *  "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 *  KIND, either express or implied.  See the License for the
 *  specific language governing permissions and limitations
 *  under the License.
 *  
 ******************************************************************************
*/


// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.energyos.espi.datacustodian.domain;

import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.energyos.espi.datacustodian.common.ApplicationInformationDataOnDemand;
import org.energyos.espi.datacustodian.common.DataCustodianApplicationStatusDataOnDemand;
import org.energyos.espi.datacustodian.common.ServiceStatusDataOnDemand;
import org.energyos.espi.datacustodian.common.ThirdPartyApplicationUseDataOnDemand;
import org.energyos.espi.datacustodian.domain.DataCustodianDataOnDemand;
import org.energyos.espi.datacustodian.domain.ThirdParty;
import org.energyos.espi.datacustodian.domain.ThirdPartyDataOnDemand;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect ThirdPartyDataOnDemand_Roo_DataOnDemand {
    
    declare @type: ThirdPartyDataOnDemand: @Component;
    
    private Random ThirdPartyDataOnDemand.rnd = new SecureRandom();
    
    private List<ThirdParty> ThirdPartyDataOnDemand.data;
    
    @Autowired
    ApplicationInformationDataOnDemand ThirdPartyDataOnDemand.applicationInformationDataOnDemand;
    
    @Autowired
    ThirdPartyApplicationUseDataOnDemand ThirdPartyDataOnDemand.thirdPartyApplicationUseDataOnDemand;
    
    @Autowired
    DataCustodianDataOnDemand ThirdPartyDataOnDemand.dataCustodianDataOnDemand;
    
    @Autowired
    DataCustodianApplicationStatusDataOnDemand ThirdPartyDataOnDemand.dataCustodianApplicationStatusDataOnDemand;
    
    @Autowired
    ServiceStatusDataOnDemand ThirdPartyDataOnDemand.serviceStatusDataOnDemand;
    
    public ThirdParty ThirdPartyDataOnDemand.getNewTransientThirdParty(int index) {
        ThirdParty obj = new ThirdParty();
        setAuthorized(obj, index);
        setDescription(obj, index);
        setName(obj, index);
        return obj;
    }
    
    public void ThirdPartyDataOnDemand.setAuthorized(ThirdParty obj, int index) {
        Boolean authorized = Boolean.TRUE;
        obj.setAuthorized(authorized);
    }
    
    public void ThirdPartyDataOnDemand.setDescription(ThirdParty obj, int index) {
        String description = "description_" + index;
        if (description.length() > 512) {
            description = description.substring(0, 512);
        }
        obj.setDescription(description);
    }
    
    public void ThirdPartyDataOnDemand.setName(ThirdParty obj, int index) {
        String name = "name_" + index;
        if (name.length() > 30) {
            name = name.substring(0, 30);
        }
        obj.setName(name);
    }
    
    public ThirdParty ThirdPartyDataOnDemand.getSpecificThirdParty(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        ThirdParty obj = data.get(index);
        Long id = obj.getId();
        return ThirdParty.findThirdParty(id);
    }
    
    public ThirdParty ThirdPartyDataOnDemand.getRandomThirdParty() {
        init();
        ThirdParty obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return ThirdParty.findThirdParty(id);
    }
    
    public boolean ThirdPartyDataOnDemand.modifyThirdParty(ThirdParty obj) {
        return false;
    }
    
    public void ThirdPartyDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = ThirdParty.findThirdPartyEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'ThirdParty' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<ThirdParty>();
        for (int i = 0; i < 10; i++) {
            ThirdParty obj = getNewTransientThirdParty(i);
            try {
                obj.persist();
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
