// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.energyos.espi.datacustodian.domain;

import org.energyos.espi.datacustodian.domain.UsagePointDataOnDemand;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect UsagePointIntegrationTest_Roo_IntegrationTest {
    
    declare @type: UsagePointIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: UsagePointIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext.xml");
    
    declare @type: UsagePointIntegrationTest: @Transactional;
    
    @Autowired
    private UsagePointDataOnDemand UsagePointIntegrationTest.dod;
    
    @Test
    public void UsagePointIntegrationTest.testCountUsagePoints() {
        org.junit.Assert.assertNotNull("Data on demand for 'UsagePoint' failed to initialize correctly", dod.getRandomUsagePoint());
        long count = org.energyos.espi.datacustodian.domain.UsagePoint.countUsagePoints();
        org.junit.Assert.assertTrue("Counter for 'UsagePoint' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void UsagePointIntegrationTest.testFindUsagePoint() {
        org.energyos.espi.datacustodian.domain.UsagePoint obj = dod.getRandomUsagePoint();
        org.junit.Assert.assertNotNull("Data on demand for 'UsagePoint' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'UsagePoint' failed to provide an identifier", id);
        obj = org.energyos.espi.datacustodian.domain.UsagePoint.findUsagePoint(id);
        org.junit.Assert.assertNotNull("Find method for 'UsagePoint' illegally returned null for id '" + id + "'", obj);
        org.junit.Assert.assertEquals("Find method for 'UsagePoint' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void UsagePointIntegrationTest.testFindAllUsagePoints() {
        org.junit.Assert.assertNotNull("Data on demand for 'UsagePoint' failed to initialize correctly", dod.getRandomUsagePoint());
        long count = org.energyos.espi.datacustodian.domain.UsagePoint.countUsagePoints();
        org.junit.Assert.assertTrue("Too expensive to perform a find all test for 'UsagePoint', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        java.util.List<org.energyos.espi.datacustodian.domain.UsagePoint> result = org.energyos.espi.datacustodian.domain.UsagePoint.findAllUsagePoints();
        org.junit.Assert.assertNotNull("Find all method for 'UsagePoint' illegally returned null", result);
        org.junit.Assert.assertTrue("Find all method for 'UsagePoint' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void UsagePointIntegrationTest.testFindUsagePointEntries() {
        org.junit.Assert.assertNotNull("Data on demand for 'UsagePoint' failed to initialize correctly", dod.getRandomUsagePoint());
        long count = org.energyos.espi.datacustodian.domain.UsagePoint.countUsagePoints();
        if (count > 20) count = 20;
        java.util.List<org.energyos.espi.datacustodian.domain.UsagePoint> result = org.energyos.espi.datacustodian.domain.UsagePoint.findUsagePointEntries(0, (int) count);
        org.junit.Assert.assertNotNull("Find entries method for 'UsagePoint' illegally returned null", result);
        org.junit.Assert.assertEquals("Find entries method for 'UsagePoint' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void UsagePointIntegrationTest.testFlush() {
        org.energyos.espi.datacustodian.domain.UsagePoint obj = dod.getRandomUsagePoint();
        org.junit.Assert.assertNotNull("Data on demand for 'UsagePoint' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'UsagePoint' failed to provide an identifier", id);
        obj = org.energyos.espi.datacustodian.domain.UsagePoint.findUsagePoint(id);
        org.junit.Assert.assertNotNull("Find method for 'UsagePoint' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyUsagePoint(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        obj.flush();
        org.junit.Assert.assertTrue("Version for 'UsagePoint' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void UsagePointIntegrationTest.testMerge() {
        org.energyos.espi.datacustodian.domain.UsagePoint obj = dod.getRandomUsagePoint();
        org.junit.Assert.assertNotNull("Data on demand for 'UsagePoint' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'UsagePoint' failed to provide an identifier", id);
        obj = org.energyos.espi.datacustodian.domain.UsagePoint.findUsagePoint(id);
        boolean modified =  dod.modifyUsagePoint(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        org.energyos.espi.datacustodian.domain.UsagePoint merged =  obj.merge();
        obj.flush();
        org.junit.Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        org.junit.Assert.assertTrue("Version for 'UsagePoint' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void UsagePointIntegrationTest.testPersist() {
        org.junit.Assert.assertNotNull("Data on demand for 'UsagePoint' failed to initialize correctly", dod.getRandomUsagePoint());
        org.energyos.espi.datacustodian.domain.UsagePoint obj = dod.getNewTransientUsagePoint(Integer.MAX_VALUE);
        org.junit.Assert.assertNotNull("Data on demand for 'UsagePoint' failed to provide a new transient entity", obj);
        org.junit.Assert.assertNull("Expected 'UsagePoint' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        org.junit.Assert.assertNotNull("Expected 'UsagePoint' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void UsagePointIntegrationTest.testRemove() {
        org.energyos.espi.datacustodian.domain.UsagePoint obj = dod.getRandomUsagePoint();
        org.junit.Assert.assertNotNull("Data on demand for 'UsagePoint' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'UsagePoint' failed to provide an identifier", id);
        obj = org.energyos.espi.datacustodian.domain.UsagePoint.findUsagePoint(id);
        obj.remove();
        obj.flush();
        org.junit.Assert.assertNull("Failed to remove 'UsagePoint' with identifier '" + id + "'", org.energyos.espi.datacustodian.domain.UsagePoint.findUsagePoint(id));
    }
    
}
