/*******************************************************************************
 * Copyright (c) 2011, 2012 EnergyOS.Org
 *
 * Licensed by EnergyOS.Org under one or more contributor license agreements.
 * See the NOTICE file distributed with this work for additional information
 * regarding copyright ownership.  The EnergyOS.org licenses this file
 * to you under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License.  You may obtain a copy
 * of the License at:
 *  
 *   http://www.apache.org/licenses/LICENSE-2.0
 *  
 *  Unless required by applicable law or agreed to in writing,
 *  software distributed under the License is distributed on an
 *  "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 *  KIND, either express or implied.  See the License for the
 *  specific language governing permissions and limitations
 *  under the License.
 *  
 ******************************************************************************
*/

// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.energyos.espi.datacustodian.common;

import java.util.List;
import org.energyos.espi.datacustodian.common.ApplicationInformation;
import org.energyos.espi.datacustodian.common.ApplicationInformationDataOnDemand;
import org.energyos.espi.datacustodian.common.ApplicationInformationIntegrationTest;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect ApplicationInformationIntegrationTest_Roo_IntegrationTest {
    
    declare @type: ApplicationInformationIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: ApplicationInformationIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: ApplicationInformationIntegrationTest: @Transactional;
    
    @Autowired
    private ApplicationInformationDataOnDemand ApplicationInformationIntegrationTest.dod;
    
    @Test
    public void ApplicationInformationIntegrationTest.testCountApplicationInformations() {
        Assert.assertNotNull("Data on demand for 'ApplicationInformation' failed to initialize correctly", dod.getRandomApplicationInformation());
        long count = ApplicationInformation.countApplicationInformations();
        Assert.assertTrue("Counter for 'ApplicationInformation' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void ApplicationInformationIntegrationTest.testFindApplicationInformation() {
        ApplicationInformation obj = dod.getRandomApplicationInformation();
        Assert.assertNotNull("Data on demand for 'ApplicationInformation' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'ApplicationInformation' failed to provide an identifier", id);
        obj = ApplicationInformation.findApplicationInformation(id);
        Assert.assertNotNull("Find method for 'ApplicationInformation' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'ApplicationInformation' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void ApplicationInformationIntegrationTest.testFindAllApplicationInformations() {
        Assert.assertNotNull("Data on demand for 'ApplicationInformation' failed to initialize correctly", dod.getRandomApplicationInformation());
        long count = ApplicationInformation.countApplicationInformations();
        Assert.assertTrue("Too expensive to perform a find all test for 'ApplicationInformation', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<ApplicationInformation> result = ApplicationInformation.findAllApplicationInformations();
        Assert.assertNotNull("Find all method for 'ApplicationInformation' illegally returned null", result);
        Assert.assertTrue("Find all method for 'ApplicationInformation' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void ApplicationInformationIntegrationTest.testFindApplicationInformationEntries() {
        Assert.assertNotNull("Data on demand for 'ApplicationInformation' failed to initialize correctly", dod.getRandomApplicationInformation());
        long count = ApplicationInformation.countApplicationInformations();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<ApplicationInformation> result = ApplicationInformation.findApplicationInformationEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'ApplicationInformation' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'ApplicationInformation' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void ApplicationInformationIntegrationTest.testFlush() {
        ApplicationInformation obj = dod.getRandomApplicationInformation();
        Assert.assertNotNull("Data on demand for 'ApplicationInformation' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'ApplicationInformation' failed to provide an identifier", id);
        obj = ApplicationInformation.findApplicationInformation(id);
        Assert.assertNotNull("Find method for 'ApplicationInformation' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyApplicationInformation(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'ApplicationInformation' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void ApplicationInformationIntegrationTest.testMergeUpdate() {
        ApplicationInformation obj = dod.getRandomApplicationInformation();
        Assert.assertNotNull("Data on demand for 'ApplicationInformation' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'ApplicationInformation' failed to provide an identifier", id);
        obj = ApplicationInformation.findApplicationInformation(id);
        boolean modified =  dod.modifyApplicationInformation(obj);
        Integer currentVersion = obj.getVersion();
        ApplicationInformation merged = (ApplicationInformation)obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'ApplicationInformation' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void ApplicationInformationIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'ApplicationInformation' failed to initialize correctly", dod.getRandomApplicationInformation());
        ApplicationInformation obj = dod.getNewTransientApplicationInformation(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'ApplicationInformation' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'ApplicationInformation' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        Assert.assertNotNull("Expected 'ApplicationInformation' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void ApplicationInformationIntegrationTest.testRemove() {
        ApplicationInformation obj = dod.getRandomApplicationInformation();
        Assert.assertNotNull("Data on demand for 'ApplicationInformation' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'ApplicationInformation' failed to provide an identifier", id);
        obj = ApplicationInformation.findApplicationInformation(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'ApplicationInformation' with identifier '" + id + "'", ApplicationInformation.findApplicationInformation(id));
    }
    
}
