/*******************************************************************************
 * Copyright (c) 2011, 2012 EnergyOS.Org
 *
 * Licensed by EnergyOS.Org under one or more contributor license agreements.
 * See the NOTICE file distributed with this work for additional information
 * regarding copyright ownership.  The EnergyOS.org licenses this file
 * to you under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License.  You may obtain a copy
 * of the License at:
 *  
 *   http://www.apache.org/licenses/LICENSE-2.0
 *  
 *  Unless required by applicable law or agreed to in writing,
 *  software distributed under the License is distributed on an
 *  "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 *  KIND, either express or implied.  See the License for the
 *  specific language governing permissions and limitations
 *  under the License.
 *  
 ******************************************************************************
*/

// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.energyos.espi.datacustodian.common;

import java.util.List;
import org.energyos.espi.datacustodian.common.DestRule;
import org.energyos.espi.datacustodian.common.DestRuleDataOnDemand;
import org.energyos.espi.datacustodian.common.DestRuleIntegrationTest;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect DestRuleIntegrationTest_Roo_IntegrationTest {
    
    declare @type: DestRuleIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: DestRuleIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: DestRuleIntegrationTest: @Transactional;
    
    @Autowired
    private DestRuleDataOnDemand DestRuleIntegrationTest.dod;
    
    @Test
    public void DestRuleIntegrationTest.testCountDestRules() {
        Assert.assertNotNull("Data on demand for 'DestRule' failed to initialize correctly", dod.getRandomDestRule());
        long count = DestRule.countDestRules();
        Assert.assertTrue("Counter for 'DestRule' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void DestRuleIntegrationTest.testFindDestRule() {
        DestRule obj = dod.getRandomDestRule();
        Assert.assertNotNull("Data on demand for 'DestRule' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'DestRule' failed to provide an identifier", id);
        obj = DestRule.findDestRule(id);
        Assert.assertNotNull("Find method for 'DestRule' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'DestRule' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void DestRuleIntegrationTest.testFindAllDestRules() {
        Assert.assertNotNull("Data on demand for 'DestRule' failed to initialize correctly", dod.getRandomDestRule());
        long count = DestRule.countDestRules();
        Assert.assertTrue("Too expensive to perform a find all test for 'DestRule', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<DestRule> result = DestRule.findAllDestRules();
        Assert.assertNotNull("Find all method for 'DestRule' illegally returned null", result);
        Assert.assertTrue("Find all method for 'DestRule' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void DestRuleIntegrationTest.testFindDestRuleEntries() {
        Assert.assertNotNull("Data on demand for 'DestRule' failed to initialize correctly", dod.getRandomDestRule());
        long count = DestRule.countDestRules();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<DestRule> result = DestRule.findDestRuleEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'DestRule' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'DestRule' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void DestRuleIntegrationTest.testFlush() {
        DestRule obj = dod.getRandomDestRule();
        Assert.assertNotNull("Data on demand for 'DestRule' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'DestRule' failed to provide an identifier", id);
        obj = DestRule.findDestRule(id);
        Assert.assertNotNull("Find method for 'DestRule' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyDestRule(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'DestRule' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void DestRuleIntegrationTest.testMergeUpdate() {
        DestRule obj = dod.getRandomDestRule();
        Assert.assertNotNull("Data on demand for 'DestRule' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'DestRule' failed to provide an identifier", id);
        obj = DestRule.findDestRule(id);
        boolean modified =  dod.modifyDestRule(obj);
        Integer currentVersion = obj.getVersion();
        DestRule merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'DestRule' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void DestRuleIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'DestRule' failed to initialize correctly", dod.getRandomDestRule());
        DestRule obj = dod.getNewTransientDestRule(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'DestRule' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'DestRule' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        Assert.assertNotNull("Expected 'DestRule' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void DestRuleIntegrationTest.testRemove() {
        DestRule obj = dod.getRandomDestRule();
        Assert.assertNotNull("Data on demand for 'DestRule' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'DestRule' failed to provide an identifier", id);
        obj = DestRule.findDestRule(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'DestRule' with identifier '" + id + "'", DestRule.findDestRule(id));
    }
    
}
