/*******************************************************************************
 * Copyright (c) 2011, 2012 EnergyOS.Org
 *
 * Licensed by EnergyOS.Org under one or more contributor license agreements.
 * See the NOTICE file distributed with this work for additional information
 * regarding copyright ownership.  The EnergyOS.org licenses this file
 * to you under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License.  You may obtain a copy
 * of the License at:
 *  
 *   http://www.apache.org/licenses/LICENSE-2.0
 *  
 *  Unless required by applicable law or agreed to in writing,
 *  software distributed under the License is distributed on an
 *  "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 *  KIND, either express or implied.  See the License for the
 *  specific language governing permissions and limitations
 *  under the License.
 *  
 ******************************************************************************
*/

// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.energyos.espi.datacustodian.common;

import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.energyos.espi.datacustodian.common.DateTimeIntervalDataOnDemand;
import org.energyos.espi.datacustodian.common.IntervalBlock;
import org.energyos.espi.datacustodian.common.IntervalBlockDataOnDemand;
import org.energyos.espi.datacustodian.common.MeterReadingDataOnDemand;
import org.energyos.espi.datacustodian.common.ReadingTypeDataOnDemand;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect IntervalBlockDataOnDemand_Roo_DataOnDemand {
    
    declare @type: IntervalBlockDataOnDemand: @Component;
    
    private Random IntervalBlockDataOnDemand.rnd = new SecureRandom();
    
    private List<IntervalBlock> IntervalBlockDataOnDemand.data;
    
    @Autowired
    private DateTimeIntervalDataOnDemand IntervalBlockDataOnDemand.dateTimeIntervalDataOnDemand;
    
    @Autowired
    private MeterReadingDataOnDemand IntervalBlockDataOnDemand.meterReadingDataOnDemand;
    
    @Autowired
    private ReadingTypeDataOnDemand IntervalBlockDataOnDemand.readingTypeDataOnDemand;
    
    public IntervalBlock IntervalBlockDataOnDemand.getNewTransientIntervalBlock(int index) {
        IntervalBlock obj = new IntervalBlock();
        setDescription(obj, index);
        setUuid(obj, index);
        return obj;
    }
    
    public void IntervalBlockDataOnDemand.setDescription(IntervalBlock obj, int index) {
        String description = "description_" + index;
        obj.setDescription(description);
    }
    
    public void IntervalBlockDataOnDemand.setUuid(IntervalBlock obj, int index) {
        String uuid = "uuid_" + index;
        obj.setUuid(uuid);
    }
    
    public IntervalBlock IntervalBlockDataOnDemand.getSpecificIntervalBlock(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        IntervalBlock obj = data.get(index);
        Long id = obj.getId();
        return IntervalBlock.findIntervalBlock(id);
    }
    
    public IntervalBlock IntervalBlockDataOnDemand.getRandomIntervalBlock() {
        init();
        IntervalBlock obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return IntervalBlock.findIntervalBlock(id);
    }
    
    public boolean IntervalBlockDataOnDemand.modifyIntervalBlock(IntervalBlock obj) {
        return false;
    }
    
    public void IntervalBlockDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = IntervalBlock.findIntervalBlockEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'IntervalBlock' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<IntervalBlock>();
        for (int i = 0; i < 10; i++) {
            IntervalBlock obj = getNewTransientIntervalBlock(i);
            try {
                obj.persist();
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
