/*******************************************************************************
 * Copyright (c) 2011, 2012 EnergyOS.Org
 *
 * Licensed by EnergyOS.Org under one or more contributor license agreements.
 * See the NOTICE file distributed with this work for additional information
 * regarding copyright ownership.  The EnergyOS.org licenses this file
 * to you under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License.  You may obtain a copy
 * of the License at:
 *  
 *   http://www.apache.org/licenses/LICENSE-2.0
 *  
 *  Unless required by applicable law or agreed to in writing,
 *  software distributed under the License is distributed on an
 *  "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 *  KIND, either express or implied.  See the License for the
 *  specific language governing permissions and limitations
 *  under the License.
 *  
 ******************************************************************************
*/

// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.energyos.espi.datacustodian.common;

import java.util.List;
import org.energyos.espi.datacustodian.common.MeterReading;
import org.energyos.espi.datacustodian.common.MeterReadingDataOnDemand;
import org.energyos.espi.datacustodian.common.MeterReadingIntegrationTest;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect MeterReadingIntegrationTest_Roo_IntegrationTest {
    
    declare @type: MeterReadingIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: MeterReadingIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: MeterReadingIntegrationTest: @Transactional;
    
    @Autowired
    private MeterReadingDataOnDemand MeterReadingIntegrationTest.dod;
    
    @Test
    public void MeterReadingIntegrationTest.testCountMeterReadings() {
        Assert.assertNotNull("Data on demand for 'MeterReading' failed to initialize correctly", dod.getRandomMeterReading());
        long count = MeterReading.countMeterReadings();
        Assert.assertTrue("Counter for 'MeterReading' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void MeterReadingIntegrationTest.testFindMeterReading() {
        MeterReading obj = dod.getRandomMeterReading();
        Assert.assertNotNull("Data on demand for 'MeterReading' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'MeterReading' failed to provide an identifier", id);
        obj = MeterReading.findMeterReading(id);
        Assert.assertNotNull("Find method for 'MeterReading' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'MeterReading' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void MeterReadingIntegrationTest.testFindAllMeterReadings() {
        Assert.assertNotNull("Data on demand for 'MeterReading' failed to initialize correctly", dod.getRandomMeterReading());
        long count = MeterReading.countMeterReadings();
        Assert.assertTrue("Too expensive to perform a find all test for 'MeterReading', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<MeterReading> result = MeterReading.findAllMeterReadings();
        Assert.assertNotNull("Find all method for 'MeterReading' illegally returned null", result);
        Assert.assertTrue("Find all method for 'MeterReading' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void MeterReadingIntegrationTest.testFindMeterReadingEntries() {
        Assert.assertNotNull("Data on demand for 'MeterReading' failed to initialize correctly", dod.getRandomMeterReading());
        long count = MeterReading.countMeterReadings();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<MeterReading> result = MeterReading.findMeterReadingEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'MeterReading' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'MeterReading' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void MeterReadingIntegrationTest.testFlush() {
        MeterReading obj = dod.getRandomMeterReading();
        Assert.assertNotNull("Data on demand for 'MeterReading' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'MeterReading' failed to provide an identifier", id);
        obj = MeterReading.findMeterReading(id);
        Assert.assertNotNull("Find method for 'MeterReading' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyMeterReading(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'MeterReading' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void MeterReadingIntegrationTest.testMergeUpdate() {
        MeterReading obj = dod.getRandomMeterReading();
        Assert.assertNotNull("Data on demand for 'MeterReading' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'MeterReading' failed to provide an identifier", id);
        obj = MeterReading.findMeterReading(id);
        boolean modified =  dod.modifyMeterReading(obj);
        Integer currentVersion = obj.getVersion();
        MeterReading merged = (MeterReading)obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'MeterReading' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void MeterReadingIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'MeterReading' failed to initialize correctly", dod.getRandomMeterReading());
        MeterReading obj = dod.getNewTransientMeterReading(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'MeterReading' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'MeterReading' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        Assert.assertNotNull("Expected 'MeterReading' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void MeterReadingIntegrationTest.testRemove() {
        MeterReading obj = dod.getRandomMeterReading();
        Assert.assertNotNull("Data on demand for 'MeterReading' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'MeterReading' failed to provide an identifier", id);
        obj = MeterReading.findMeterReading(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'MeterReading' with identifier '" + id + "'", MeterReading.findMeterReading(id));
    }
    
}
