/*******************************************************************************
 * Copyright (c) 2011, 2012 EnergyOS.Org
 *
 * Licensed by EnergyOS.Org under one or more contributor license agreements.
 * See the NOTICE file distributed with this work for additional information
 * regarding copyright ownership.  The EnergyOS.org licenses this file
 * to you under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License.  You may obtain a copy
 * of the License at:
 *  
 *   http://www.apache.org/licenses/LICENSE-2.0
 *  
 *  Unless required by applicable law or agreed to in writing,
 *  software distributed under the License is distributed on an
 *  "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 *  KIND, either express or implied.  See the License for the
 *  specific language governing permissions and limitations
 *  under the License.
 *  
 ******************************************************************************
*/


// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.energyos.espi.datacustodian.common;

import java.util.List;
import org.energyos.espi.datacustodian.common.QualityOfReading;
import org.energyos.espi.datacustodian.common.QualityOfReadingDataOnDemand;
import org.energyos.espi.datacustodian.common.QualityOfReadingIntegrationTest;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect QualityOfReadingIntegrationTest_Roo_IntegrationTest {
    
    declare @type: QualityOfReadingIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: QualityOfReadingIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: QualityOfReadingIntegrationTest: @Transactional;
    
    @Autowired
    QualityOfReadingDataOnDemand QualityOfReadingIntegrationTest.dod;
    
    @Test
    public void QualityOfReadingIntegrationTest.testCountQualityOfReadings() {
        Assert.assertNotNull("Data on demand for 'QualityOfReading' failed to initialize correctly", dod.getRandomQualityOfReading());
        long count = QualityOfReading.countQualityOfReadings();
        Assert.assertTrue("Counter for 'QualityOfReading' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void QualityOfReadingIntegrationTest.testFindQualityOfReading() {
        QualityOfReading obj = dod.getRandomQualityOfReading();
        Assert.assertNotNull("Data on demand for 'QualityOfReading' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'QualityOfReading' failed to provide an identifier", id);
        obj = QualityOfReading.findQualityOfReading(id);
        Assert.assertNotNull("Find method for 'QualityOfReading' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'QualityOfReading' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void QualityOfReadingIntegrationTest.testFindAllQualityOfReadings() {
        Assert.assertNotNull("Data on demand for 'QualityOfReading' failed to initialize correctly", dod.getRandomQualityOfReading());
        long count = QualityOfReading.countQualityOfReadings();
        Assert.assertTrue("Too expensive to perform a find all test for 'QualityOfReading', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<QualityOfReading> result = QualityOfReading.findAllQualityOfReadings();
        Assert.assertNotNull("Find all method for 'QualityOfReading' illegally returned null", result);
        Assert.assertTrue("Find all method for 'QualityOfReading' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void QualityOfReadingIntegrationTest.testFindQualityOfReadingEntries() {
        Assert.assertNotNull("Data on demand for 'QualityOfReading' failed to initialize correctly", dod.getRandomQualityOfReading());
        long count = QualityOfReading.countQualityOfReadings();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<QualityOfReading> result = QualityOfReading.findQualityOfReadingEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'QualityOfReading' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'QualityOfReading' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void QualityOfReadingIntegrationTest.testFlush() {
        QualityOfReading obj = dod.getRandomQualityOfReading();
        Assert.assertNotNull("Data on demand for 'QualityOfReading' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'QualityOfReading' failed to provide an identifier", id);
        obj = QualityOfReading.findQualityOfReading(id);
        Assert.assertNotNull("Find method for 'QualityOfReading' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyQualityOfReading(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'QualityOfReading' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void QualityOfReadingIntegrationTest.testMergeUpdate() {
        QualityOfReading obj = dod.getRandomQualityOfReading();
        Assert.assertNotNull("Data on demand for 'QualityOfReading' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'QualityOfReading' failed to provide an identifier", id);
        obj = QualityOfReading.findQualityOfReading(id);
        boolean modified =  dod.modifyQualityOfReading(obj);
        Integer currentVersion = obj.getVersion();
        QualityOfReading merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'QualityOfReading' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void QualityOfReadingIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'QualityOfReading' failed to initialize correctly", dod.getRandomQualityOfReading());
        QualityOfReading obj = dod.getNewTransientQualityOfReading(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'QualityOfReading' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'QualityOfReading' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        Assert.assertNotNull("Expected 'QualityOfReading' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void QualityOfReadingIntegrationTest.testRemove() {
        QualityOfReading obj = dod.getRandomQualityOfReading();
        Assert.assertNotNull("Data on demand for 'QualityOfReading' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'QualityOfReading' failed to provide an identifier", id);
        obj = QualityOfReading.findQualityOfReading(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'QualityOfReading' with identifier '" + id + "'", QualityOfReading.findQualityOfReading(id));
    }
    
}
