/*******************************************************************************
 * Copyright (c) 2011, 2012 EnergyOS.Org
 *
 * Licensed by EnergyOS.Org under one or more contributor license agreements.
 * See the NOTICE file distributed with this work for additional information
 * regarding copyright ownership.  The EnergyOS.org licenses this file
 * to you under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License.  You may obtain a copy
 * of the License at:
 *  
 *   http://www.apache.org/licenses/LICENSE-2.0
 *  
 *  Unless required by applicable law or agreed to in writing,
 *  software distributed under the License is distributed on an
 *  "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 *  KIND, either express or implied.  See the License for the
 *  specific language governing permissions and limitations
 *  under the License.
 *  
 ******************************************************************************
*/

// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.energyos.espi.datacustodian.common;

import java.util.List;
import org.energyos.espi.datacustodian.common.ReadingInterharmonic;
import org.energyos.espi.datacustodian.common.ReadingInterharmonicDataOnDemand;
import org.energyos.espi.datacustodian.common.ReadingInterharmonicIntegrationTest;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect ReadingInterharmonicIntegrationTest_Roo_IntegrationTest {
    
    declare @type: ReadingInterharmonicIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: ReadingInterharmonicIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: ReadingInterharmonicIntegrationTest: @Transactional;
    
    @Autowired
    private ReadingInterharmonicDataOnDemand ReadingInterharmonicIntegrationTest.dod;
    
    @Test
    public void ReadingInterharmonicIntegrationTest.testCountReadingInterharmonics() {
        Assert.assertNotNull("Data on demand for 'ReadingInterharmonic' failed to initialize correctly", dod.getRandomReadingInterharmonic());
        long count = ReadingInterharmonic.countReadingInterharmonics();
        Assert.assertTrue("Counter for 'ReadingInterharmonic' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void ReadingInterharmonicIntegrationTest.testFindReadingInterharmonic() {
        ReadingInterharmonic obj = dod.getRandomReadingInterharmonic();
        Assert.assertNotNull("Data on demand for 'ReadingInterharmonic' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'ReadingInterharmonic' failed to provide an identifier", id);
        obj = ReadingInterharmonic.findReadingInterharmonic(id);
        Assert.assertNotNull("Find method for 'ReadingInterharmonic' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'ReadingInterharmonic' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void ReadingInterharmonicIntegrationTest.testFindAllReadingInterharmonics() {
        Assert.assertNotNull("Data on demand for 'ReadingInterharmonic' failed to initialize correctly", dod.getRandomReadingInterharmonic());
        long count = ReadingInterharmonic.countReadingInterharmonics();
        Assert.assertTrue("Too expensive to perform a find all test for 'ReadingInterharmonic', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<ReadingInterharmonic> result = ReadingInterharmonic.findAllReadingInterharmonics();
        Assert.assertNotNull("Find all method for 'ReadingInterharmonic' illegally returned null", result);
        Assert.assertTrue("Find all method for 'ReadingInterharmonic' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void ReadingInterharmonicIntegrationTest.testFindReadingInterharmonicEntries() {
        Assert.assertNotNull("Data on demand for 'ReadingInterharmonic' failed to initialize correctly", dod.getRandomReadingInterharmonic());
        long count = ReadingInterharmonic.countReadingInterharmonics();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<ReadingInterharmonic> result = ReadingInterharmonic.findReadingInterharmonicEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'ReadingInterharmonic' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'ReadingInterharmonic' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void ReadingInterharmonicIntegrationTest.testFlush() {
        ReadingInterharmonic obj = dod.getRandomReadingInterharmonic();
        Assert.assertNotNull("Data on demand for 'ReadingInterharmonic' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'ReadingInterharmonic' failed to provide an identifier", id);
        obj = ReadingInterharmonic.findReadingInterharmonic(id);
        Assert.assertNotNull("Find method for 'ReadingInterharmonic' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyReadingInterharmonic(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'ReadingInterharmonic' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void ReadingInterharmonicIntegrationTest.testMergeUpdate() {
        ReadingInterharmonic obj = dod.getRandomReadingInterharmonic();
        Assert.assertNotNull("Data on demand for 'ReadingInterharmonic' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'ReadingInterharmonic' failed to provide an identifier", id);
        obj = ReadingInterharmonic.findReadingInterharmonic(id);
        boolean modified =  dod.modifyReadingInterharmonic(obj);
        Integer currentVersion = obj.getVersion();
        ReadingInterharmonic merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'ReadingInterharmonic' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void ReadingInterharmonicIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'ReadingInterharmonic' failed to initialize correctly", dod.getRandomReadingInterharmonic());
        ReadingInterharmonic obj = dod.getNewTransientReadingInterharmonic(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'ReadingInterharmonic' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'ReadingInterharmonic' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        Assert.assertNotNull("Expected 'ReadingInterharmonic' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void ReadingInterharmonicIntegrationTest.testRemove() {
        ReadingInterharmonic obj = dod.getRandomReadingInterharmonic();
        Assert.assertNotNull("Data on demand for 'ReadingInterharmonic' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'ReadingInterharmonic' failed to provide an identifier", id);
        obj = ReadingInterharmonic.findReadingInterharmonic(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'ReadingInterharmonic' with identifier '" + id + "'", ReadingInterharmonic.findReadingInterharmonic(id));
    }
    
}
