/*******************************************************************************
 * Copyright (c) 2011, 2012 EnergyOS.Org
 *
 * Licensed by EnergyOS.Org under one or more contributor license agreements.
 * See the NOTICE file distributed with this work for additional information
 * regarding copyright ownership.  The EnergyOS.org licenses this file
 * to you under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License.  You may obtain a copy
 * of the License at:
 *  
 *   http://www.apache.org/licenses/LICENSE-2.0
 *  
 *  Unless required by applicable law or agreed to in writing,
 *  software distributed under the License is distributed on an
 *  "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 *  KIND, either express or implied.  See the License for the
 *  specific language governing permissions and limitations
 *  under the License.
 *  
 ******************************************************************************
*/

// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.energyos.espi.datacustodian.common;

import java.util.List;
import org.energyos.espi.datacustodian.common.StatusCode;
import org.energyos.espi.datacustodian.common.StatusCodeDataOnDemand;
import org.energyos.espi.datacustodian.common.StatusCodeIntegrationTest;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect StatusCodeIntegrationTest_Roo_IntegrationTest {
    
    declare @type: StatusCodeIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: StatusCodeIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: StatusCodeIntegrationTest: @Transactional;
    
    @Autowired
    private StatusCodeDataOnDemand StatusCodeIntegrationTest.dod;
    
    @Test
    public void StatusCodeIntegrationTest.testCountStatusCodes() {
        Assert.assertNotNull("Data on demand for 'StatusCode' failed to initialize correctly", dod.getRandomStatusCode());
        long count = StatusCode.countStatusCodes();
        Assert.assertTrue("Counter for 'StatusCode' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void StatusCodeIntegrationTest.testFindStatusCode() {
        StatusCode obj = dod.getRandomStatusCode();
        Assert.assertNotNull("Data on demand for 'StatusCode' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'StatusCode' failed to provide an identifier", id);
        obj = StatusCode.findStatusCode(id);
        Assert.assertNotNull("Find method for 'StatusCode' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'StatusCode' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void StatusCodeIntegrationTest.testFindAllStatusCodes() {
        Assert.assertNotNull("Data on demand for 'StatusCode' failed to initialize correctly", dod.getRandomStatusCode());
        long count = StatusCode.countStatusCodes();
        Assert.assertTrue("Too expensive to perform a find all test for 'StatusCode', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<StatusCode> result = StatusCode.findAllStatusCodes();
        Assert.assertNotNull("Find all method for 'StatusCode' illegally returned null", result);
        Assert.assertTrue("Find all method for 'StatusCode' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void StatusCodeIntegrationTest.testFindStatusCodeEntries() {
        Assert.assertNotNull("Data on demand for 'StatusCode' failed to initialize correctly", dod.getRandomStatusCode());
        long count = StatusCode.countStatusCodes();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<StatusCode> result = StatusCode.findStatusCodeEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'StatusCode' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'StatusCode' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void StatusCodeIntegrationTest.testFlush() {
        StatusCode obj = dod.getRandomStatusCode();
        Assert.assertNotNull("Data on demand for 'StatusCode' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'StatusCode' failed to provide an identifier", id);
        obj = StatusCode.findStatusCode(id);
        Assert.assertNotNull("Find method for 'StatusCode' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyStatusCode(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'StatusCode' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void StatusCodeIntegrationTest.testMergeUpdate() {
        StatusCode obj = dod.getRandomStatusCode();
        Assert.assertNotNull("Data on demand for 'StatusCode' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'StatusCode' failed to provide an identifier", id);
        obj = StatusCode.findStatusCode(id);
        boolean modified =  dod.modifyStatusCode(obj);
        Integer currentVersion = obj.getVersion();
        StatusCode merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'StatusCode' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void StatusCodeIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'StatusCode' failed to initialize correctly", dod.getRandomStatusCode());
        StatusCode obj = dod.getNewTransientStatusCode(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'StatusCode' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'StatusCode' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        Assert.assertNotNull("Expected 'StatusCode' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void StatusCodeIntegrationTest.testRemove() {
        StatusCode obj = dod.getRandomStatusCode();
        Assert.assertNotNull("Data on demand for 'StatusCode' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'StatusCode' failed to provide an identifier", id);
        obj = StatusCode.findStatusCode(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'StatusCode' with identifier '" + id + "'", StatusCode.findStatusCode(id));
    }
    
}
