// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.energyos.espi.datacustodian.domain;

import org.energyos.espi.datacustodian.domain.IntervalReadingDataOnDemand;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect IntervalReadingIntegrationTest_Roo_IntegrationTest {
    
    declare @type: IntervalReadingIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: IntervalReadingIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext.xml");
    
    declare @type: IntervalReadingIntegrationTest: @Transactional;
    
    @Autowired
    private IntervalReadingDataOnDemand IntervalReadingIntegrationTest.dod;
    
    @Test
    public void IntervalReadingIntegrationTest.testCountIntervalReadings() {
        org.junit.Assert.assertNotNull("Data on demand for 'IntervalReading' failed to initialize correctly", dod.getRandomIntervalReading());
        long count = org.energyos.espi.datacustodian.domain.IntervalReading.countIntervalReadings();
        org.junit.Assert.assertTrue("Counter for 'IntervalReading' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void IntervalReadingIntegrationTest.testFindIntervalReading() {
        org.energyos.espi.datacustodian.domain.IntervalReading obj = dod.getRandomIntervalReading();
        org.junit.Assert.assertNotNull("Data on demand for 'IntervalReading' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'IntervalReading' failed to provide an identifier", id);
        obj = org.energyos.espi.datacustodian.domain.IntervalReading.findIntervalReading(id);
        org.junit.Assert.assertNotNull("Find method for 'IntervalReading' illegally returned null for id '" + id + "'", obj);
        org.junit.Assert.assertEquals("Find method for 'IntervalReading' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void IntervalReadingIntegrationTest.testFindAllIntervalReadings() {
        org.junit.Assert.assertNotNull("Data on demand for 'IntervalReading' failed to initialize correctly", dod.getRandomIntervalReading());
        long count = org.energyos.espi.datacustodian.domain.IntervalReading.countIntervalReadings();
        org.junit.Assert.assertTrue("Too expensive to perform a find all test for 'IntervalReading', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        java.util.List<org.energyos.espi.datacustodian.domain.IntervalReading> result = org.energyos.espi.datacustodian.domain.IntervalReading.findAllIntervalReadings();
        org.junit.Assert.assertNotNull("Find all method for 'IntervalReading' illegally returned null", result);
        org.junit.Assert.assertTrue("Find all method for 'IntervalReading' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void IntervalReadingIntegrationTest.testFindIntervalReadingEntries() {
        org.junit.Assert.assertNotNull("Data on demand for 'IntervalReading' failed to initialize correctly", dod.getRandomIntervalReading());
        long count = org.energyos.espi.datacustodian.domain.IntervalReading.countIntervalReadings();
        if (count > 20) count = 20;
        java.util.List<org.energyos.espi.datacustodian.domain.IntervalReading> result = org.energyos.espi.datacustodian.domain.IntervalReading.findIntervalReadingEntries(0, (int) count);
        org.junit.Assert.assertNotNull("Find entries method for 'IntervalReading' illegally returned null", result);
        org.junit.Assert.assertEquals("Find entries method for 'IntervalReading' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void IntervalReadingIntegrationTest.testFlush() {
        org.energyos.espi.datacustodian.domain.IntervalReading obj = dod.getRandomIntervalReading();
        org.junit.Assert.assertNotNull("Data on demand for 'IntervalReading' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'IntervalReading' failed to provide an identifier", id);
        obj = org.energyos.espi.datacustodian.domain.IntervalReading.findIntervalReading(id);
        org.junit.Assert.assertNotNull("Find method for 'IntervalReading' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyIntervalReading(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        obj.flush();
        org.junit.Assert.assertTrue("Version for 'IntervalReading' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void IntervalReadingIntegrationTest.testMerge() {
        org.energyos.espi.datacustodian.domain.IntervalReading obj = dod.getRandomIntervalReading();
        org.junit.Assert.assertNotNull("Data on demand for 'IntervalReading' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'IntervalReading' failed to provide an identifier", id);
        obj = org.energyos.espi.datacustodian.domain.IntervalReading.findIntervalReading(id);
        boolean modified =  dod.modifyIntervalReading(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        org.energyos.espi.datacustodian.domain.IntervalReading merged =  obj.merge();
        obj.flush();
        org.junit.Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        org.junit.Assert.assertTrue("Version for 'IntervalReading' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void IntervalReadingIntegrationTest.testPersist() {
        org.junit.Assert.assertNotNull("Data on demand for 'IntervalReading' failed to initialize correctly", dod.getRandomIntervalReading());
        org.energyos.espi.datacustodian.domain.IntervalReading obj = dod.getNewTransientIntervalReading(Integer.MAX_VALUE);
        org.junit.Assert.assertNotNull("Data on demand for 'IntervalReading' failed to provide a new transient entity", obj);
        org.junit.Assert.assertNull("Expected 'IntervalReading' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        org.junit.Assert.assertNotNull("Expected 'IntervalReading' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void IntervalReadingIntegrationTest.testRemove() {
        org.energyos.espi.datacustodian.domain.IntervalReading obj = dod.getRandomIntervalReading();
        org.junit.Assert.assertNotNull("Data on demand for 'IntervalReading' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'IntervalReading' failed to provide an identifier", id);
        obj = org.energyos.espi.datacustodian.domain.IntervalReading.findIntervalReading(id);
        obj.remove();
        obj.flush();
        org.junit.Assert.assertNull("Failed to remove 'IntervalReading' with identifier '" + id + "'", org.energyos.espi.datacustodian.domain.IntervalReading.findIntervalReading(id));
    }
    
}
