// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.energyos.espi.datacustodian.domain;

import java.lang.String;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.energyos.espi.datacustodian.domain.MeterReading;
import org.energyos.espi.datacustodian.domain.UsagePoint;
import org.energyos.espi.datacustodian.domain.UsagePointDataOnDemand;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect MeterReadingDataOnDemand_Roo_DataOnDemand {
    
    declare @type: MeterReadingDataOnDemand: @Component;
    
    private Random MeterReadingDataOnDemand.rnd = new SecureRandom();
    
    private List<MeterReading> MeterReadingDataOnDemand.data;
    
    @Autowired
    private UsagePointDataOnDemand MeterReadingDataOnDemand.usagePointDataOnDemand;
    
    public MeterReading MeterReadingDataOnDemand.getNewTransientMeterReading(int index) {
        MeterReading obj = new MeterReading();
        setDescription(obj, index);
        setName(obj, index);
        setUsagePoint(obj, index);
        return obj;
    }
    
    public void MeterReadingDataOnDemand.setDescription(MeterReading obj, int index) {
        String description = "description_" + index;
        if (description.length() > 512) {
            description = description.substring(0, 512);
        }
        obj.setDescription(description);
    }
    
    public void MeterReadingDataOnDemand.setName(MeterReading obj, int index) {
        String name = "name_" + index;
        if (name.length() > 30) {
            name = name.substring(0, 30);
        }
        obj.setName(name);
    }
    
    public void MeterReadingDataOnDemand.setUsagePoint(MeterReading obj, int index) {
        UsagePoint usagePoint = usagePointDataOnDemand.getRandomUsagePoint();
        obj.setUsagePoint(usagePoint);
    }
    
    public MeterReading MeterReadingDataOnDemand.getSpecificMeterReading(int index) {
        init();
        if (index < 0) index = 0;
        if (index > (data.size() - 1)) index = data.size() - 1;
        MeterReading obj = data.get(index);
        return MeterReading.findMeterReading(obj.getId());
    }
    
    public MeterReading MeterReadingDataOnDemand.getRandomMeterReading() {
        init();
        MeterReading obj = data.get(rnd.nextInt(data.size()));
        return MeterReading.findMeterReading(obj.getId());
    }
    
    public boolean MeterReadingDataOnDemand.modifyMeterReading(MeterReading obj) {
        return false;
    }
    
    public void MeterReadingDataOnDemand.init() {
        data = MeterReading.findMeterReadingEntries(0, 10);
        if (data == null) throw new IllegalStateException("Find entries implementation for 'MeterReading' illegally returned null");
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<org.energyos.espi.datacustodian.domain.MeterReading>();
        for (int i = 0; i < 10; i++) {
            MeterReading obj = getNewTransientMeterReading(i);
            try {
                obj.persist();
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> it = e.getConstraintViolations().iterator(); it.hasNext();) {
                    ConstraintViolation<?> cv = it.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
